name: test_openscad_discovery

on:
  workflow_dispatch

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install OpenSCAD
        run: brew install openscad

      - name: Install jupyterscad
        run: pip install --upgrade jupyterscad

      - name: Render stl
        run: python -c "from jupyterscad import render_stl; render_stl('cube([3,3,3]);', 'output.stl')"

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install OpenSCAD
        run: sudo apt-get install -y openscad

      - name: Install jupyterscad
        run: pip install --upgrade jupyterscad

      - name: Render stl
        run: python -c "from jupyterscad import render_stl; render_stl('cube([3,3,3]);', 'output.stl')"

  windows:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Download and Install OpenSCAD
        shell: pwsh
        run: |
          (New-Object System.Net.WebClient).DownloadFile('https://files.openscad.org/OpenSCAD-2021.01-x86-32-Installer.exe', 'OpenSCAD-2021.01-x86-32-Installer.exe')
          .\OpenSCAD-2021.01-x86-32-Installer.exe

      - name: Install jupyterscad
        run: pip install --upgrade jupyterscad

      - name: Render stl
        run: python -c "from jupyterscad import render_stl; render_stl('cube([3,3,3]);', 'output.stl')"

